version: "3.9"
services:
  useritem-api-service:
    image: kunocls/r0937868-2ccs02-apidev:latest
    ports:
      - "8000:8000"
    volumes:
      - sqlite_useritems_volume:/code/db
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'user'  # Change this to your desired database name
      MYSQL_USER: 'user'  # Change this to your desired username
      MYSQL_PASSWORD: 'user'  # Change this to your desired password
      MYSQL_ROOT_PASSWORD: 'user'  # Change this to your desired root password
    ports:
      - "3306:3306"  # Change the port mapping if needed

volumes:
  sqlite_useritems_volume:
