version: "3.9"
services:
 useritem-api-service:
  image: kunocls/r0937868-2ccs02-apidev:latest
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
